project_id = "iwnrzusyyfboidbhtgfd"

[functions.monnify]
verify_jwt = true

[functions.monnify-webhook]
verify_jwt = false

[functions.ngnb-treasury]
verify_jwt = true

[functions.ngnb-swap]
verify_jwt = true

[functions.bimcoin-swap]
verify_jwt = true
